# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

import torch
from semilearn.core.algorithmbase import AlgorithmBase
from semilearn.core.utils import ALGORITHMS
from semilearn.algorithms.hooks import PseudoLabelingHook, FixedThresholdingHook
from semilearn.algorithms.utils import SSL_Argument, str2bool


@ALGORITHMS.register('flowmatch')
class FlowMatch(AlgorithmBase):
    """
    FlowMatch: Semi-Supervised Learning via Path-Integrated Consistency
    over Augmentation Fields.

    Full paper implementation:
      - Trajectory views generated by dataset (progressive RandAugment, K levels)
      - Teacher (EMA) predicts all trajectory views → no gradient leak
      - Best-k trajectory pseudo-label supervises the WEAK view (Eq. 2-5)
      - Trajectory-level consistency loss L_cons on teacher predictions (Eq. 8)
      - LyapEMA: adaptive EMA decay based on student-teacher parameter distance (Eq. 6-7)
      - Lyapunov stability loss: L_lyap = λ||θ_t - θ_s||² pulls student toward teacher (Eq. 11)

    Backward-compatible: old configs (a1_enable etc.) still work via the legacy path.
    """

    def __init__(self, args, net_builder, tb_log=None, logger=None):
        super().__init__(args, net_builder, tb_log, logger)
        self.init(
            T=args.T,
            p_cutoff=args.p_cutoff,
            hard_label=args.hard_label,
            traj_steps=args.traj_steps,
            traj_n_ops=getattr(args, 'traj_n_ops', 2),
            lambda_cons=getattr(args, 'lambda_cons', 0.0),
            lyap_enable=getattr(args, 'lyap_enable', False),
            lyap_gamma=getattr(args, 'lyap_gamma', 0.02),
            lyap_lambda=getattr(args, 'lyap_lambda', 0.0),
            # Legacy flags kept for old configs
            a1_enable=args.a1_enable,
            a2_enable=args.a2_enable,
            a3_enable=args.a3_enable,
            a3_warmup_iter=args.a3_warmup_iter,
            a3_mix_ratio=args.a3_mix_ratio,
            a3_ramp_iter=args.a3_ramp_iter,
            a4_enable=args.a4_enable,
            a41_enable=args.a41_enable,
            lambda_a41_traj=args.lambda_a41_traj,
            a32_enable=args.a32_enable,
            traj_drop_max=args.traj_drop_max,
            traj_noise_max=args.traj_noise_max,
            traj_jitter_max=args.traj_jitter_max,
            freeze_traj_bn=args.freeze_traj_bn,
        )

    def init(self, T, p_cutoff, hard_label=True,
             traj_steps=5, traj_n_ops=2,
             lambda_cons=0.0,
             lyap_enable=False, lyap_gamma=0.02, lyap_lambda=0.0,
             # Legacy
             a1_enable=False, a2_enable=False, a3_enable=False,
             a3_warmup_iter=20000, a3_mix_ratio=0.2, a3_ramp_iter=30000,
             a4_enable=False, a41_enable=False, lambda_a41_traj=0.5,
             a32_enable=False, traj_drop_max=0.3, traj_noise_max=0.06,
             traj_jitter_max=0.2, freeze_traj_bn=False):
        self.T = T
        self.p_cutoff = p_cutoff
        self.use_hard_label = hard_label
        self.traj_steps = traj_steps
        self.traj_n_ops = traj_n_ops
        self.lambda_cons = lambda_cons
        self.lyap_enable = lyap_enable
        self.lyap_gamma = lyap_gamma
        self.lyap_lambda = lyap_lambda
        # Legacy
        self.a1_enable = a1_enable
        self.a2_enable = a2_enable
        self.a3_enable = a3_enable
        self.a3_warmup_iter = a3_warmup_iter
        self.a3_mix_ratio = a3_mix_ratio
        self.a3_ramp_iter = a3_ramp_iter
        self.a4_enable = a4_enable
        self.a41_enable = a41_enable
        self.lambda_a41_traj = lambda_a41_traj
        self.a32_enable = a32_enable
        self.traj_drop_max = traj_drop_max
        self.traj_noise_max = traj_noise_max
        self.traj_jitter_max = traj_jitter_max
        self.freeze_traj_bn = freeze_traj_bn
        self._last_alpha_t = 0.999   # for logging

    def set_hooks(self):
        self.register_hook(PseudoLabelingHook(), "PseudoLabelingHook")
        self.register_hook(FixedThresholdingHook(), "MaskingHook")
        super().set_hooks()

    # ── Legacy trajectory (for backward compat with old a1/a2/a3/a32 configs) ──
    def _make_traj_views_legacy(self, x_w, x_s):
        alphas = torch.linspace(0.0, 1.0, steps=self.traj_steps, device=x_w.device)
        views = []
        for a in alphas:
            if self.a32_enable:
                x = x_w.clone()
                j = float(a * self.traj_jitter_max)
                if j > 1e-6:
                    b = 1.0 + (torch.rand(x.size(0), 1, 1, 1, device=x.device) * 2 - 1) * j
                    c = 1.0 + (torch.rand(x.size(0), 1, 1, 1, device=x.device) * 2 - 1) * j
                    x_mean = x.mean(dim=(2, 3), keepdim=True)
                    x = (x - x_mean) * c + x_mean
                    x = x * b
                nstd = float(a * self.traj_noise_max)
                if nstd > 1e-6:
                    x = x + torch.randn_like(x) * nstd
                drop_p = float(a * self.traj_drop_max)
                if drop_p > 1e-6:
                    mask = (torch.rand_like(x[:, :1, :, :]) > drop_p).float()
                    x = x * mask
                x = x.clamp(-3.0, 3.0)
            else:
                x = (1.0 - a) * x_w + a * x_s
                drop_p = float(a * self.traj_drop_max)
                if drop_p > 1e-6:
                    mask = (torch.rand_like(x[:, :1, :, :]) > drop_p).float()
                    x = x * mask
            views.append(x)
        return views

    # ── LyapEMA: compute adaptive decay and store for EMAHook ──────────────────
    def _update_lyap_decay(self):
        """
        Compute adaptive EMA decay α_t and write into self.ema.decay so that
        EMAHook.after_train_step uses it automatically. (Eq. 6-7)

        Reparameterized to α_t ∈ [ema_m, 1.0]:
          raw  = 2·sigmoid(γ·||θ_s - θ_t||₂) - 1  ∈ [0, 1)
          α_t  = ema_m + (1 - ema_m) · raw

        Behaviour:
          dist → 0   (student ≈ teacher): raw → 0  → α_t = ema_m  (standard EMA speed)
          dist → ∞   (student diverged) : raw → 1  → α_t → 1.0   (teacher freezes)

        This is model-size-agnostic because the mapping always spans [ema_m, 1.0]
        regardless of the absolute scale of dist.
        """
        if not hasattr(self, 'ema') or self.ema is None:
            return
        dist_sq = 0.0
        for name, p_s in self.model.named_parameters():
            p_t = self.ema.shadow.get(name)
            if p_t is not None:
                dist_sq = dist_sq + (p_s.data - p_t).pow(2).sum()
        param_dist = dist_sq.sqrt()
        raw = 2.0 * torch.sigmoid(torch.tensor(self.lyap_gamma * param_dist.item())).item() - 1.0
        alpha_t = self.ema_m + (1.0 - self.ema_m) * raw   # ∈ [ema_m, 1.0)
        self.ema.decay = alpha_t
        self._last_alpha_t = alpha_t

    def train_step(self, x_lb, y_lb, x_ulb_w, x_ulb_s, x_ulb_traj=None):
        num_lb = y_lb.shape[0]

        with self.amp_cm():
            # ── Main forward pass (student) ─────────────────────────────────────
            if self.use_cat:
                inputs = torch.cat((x_lb, x_ulb_w, x_ulb_s))
                outputs = self.model(inputs)
                logits_x_lb = outputs['logits'][:num_lb]
                logits_x_ulb_w, logits_x_ulb_s = outputs['logits'][num_lb:].chunk(2)
                feats_x_lb = outputs['feat'][:num_lb]
                feats_x_ulb_w, feats_x_ulb_s = outputs['feat'][num_lb:].chunk(2)
            else:
                outs_x_lb = self.model(x_lb)
                logits_x_lb = outs_x_lb['logits']
                feats_x_lb = outs_x_lb['feat']
                outs_x_ulb_s = self.model(x_ulb_s)
                logits_x_ulb_s = outs_x_ulb_s['logits']
                feats_x_ulb_s = outs_x_ulb_s['feat']
                with torch.no_grad():
                    outs_x_ulb_w = self.model(x_ulb_w)
                    logits_x_ulb_w = outs_x_ulb_w['logits']
                    feats_x_ulb_w = outs_x_ulb_w['feat']

            feat_dict = {'x_lb': feats_x_lb, 'x_ulb_w': feats_x_ulb_w, 'x_ulb_s': feats_x_ulb_s}

            # ── Supervised loss ─────────────────────────────────────────────────
            sup_loss = self.ce_loss(logits_x_lb, y_lb, reduction='mean')
            probs_x_ulb_w = self.compute_prob(logits_x_ulb_w.detach())

            if self.registered_hook("DistAlignHook"):
                probs_x_ulb_w = self.call_hook("dist_align", "DistAlignHook",
                                               probs_x_ulb=probs_x_ulb_w.detach())

            # ── NEW PATH: paper-style trajectory from dataset ───────────────────
            # x_ulb_traj is [B, K, C, H, W] produced by TrajectoryTransform in the dataset.
            # All K views are forward-passed through the EMA teacher (no gradient).
            traj_conf_mean = torch.tensor(0.0, device=x_ulb_w.device)
            traj_probs = None   # [K, B, C] — teacher predictions on trajectory

            if x_ulb_traj is not None:
                B, K, C, H, W = x_ulb_traj.shape
                traj_flat = x_ulb_traj.view(B * K, C, H, W)
                with torch.no_grad():
                    traj_logits = self.ema_model(traj_flat)['logits']   # [B*K, num_cls]
                traj_probs = self.compute_prob(traj_logits).view(B, K, -1).permute(1, 0, 2)   # [K, B, C]
                traj_conf_mean = traj_probs.max(dim=-1)[0].mean()

                # Trajectory-averaged pseudo-label p̄ (Eq. 2)
                p_bar = traj_probs.mean(dim=0)                              # [B, C]

                # Best-k selection (Eq. 3-4): k* = argmax_k max_c p^(k)_{b,c}
                conf_per_k = traj_probs.max(dim=-1)[0]                      # [K, B]
                best_k = conf_per_k.argmax(dim=0)                           # [B]
                b_idx = torch.arange(B, device=best_k.device)
                p_star = traj_probs[best_k, b_idx]                          # [B, C]

                # Mask: gate on student WEAK-view confidence (reliable from step 1,
                # like FixMatch).  p_star from teacher trajectory is unreliable early
                # on and leads to class collapse when used for gating.
                mask = self.call_hook("masking", "MaskingHook",
                                     logits_x_ulb=probs_x_ulb_w, softmax_x_ulb=False)

                # Pseudo-label from best-k trajectory (Eq. 4)
                pseudo_label = self.call_hook(
                    "gen_ulb_targets", "PseudoLabelingHook",
                    logits=p_star,
                    use_hard_label=self.use_hard_label,
                    T=self.T,
                    softmax=False,
                )

                # Unsupervised loss: trajectory pseudo → STRONG view (Eq. 5 variant)
                # Supervising the strong view (not weak) forces augmentation invariance
                # and prevents easy class collapse on the low-aug weak view.
                unsup_loss = self.consistency_loss(logits_x_ulb_s, pseudo_label, 'ce', mask=mask)

            # ── LEGACY PATH: old a1/a2/a3/a3.1/a3.2/a4/a41 configs ────────────
            elif self.a1_enable or self.a2_enable or self.a3_enable:
                with torch.no_grad():
                    traj_views = self._make_traj_views_legacy(x_ulb_w, x_ulb_s)
                    traj_probs_list = []
                    confs = []
                    if self.freeze_traj_bn:
                        self.model.eval()
                    for xv in traj_views:
                        logits_v = self.model(xv)['logits']
                        p_v = self.compute_prob(logits_v)
                        traj_probs_list.append(p_v)
                        confs.append(p_v.max(dim=-1)[0])
                    traj_probs = torch.stack(traj_probs_list, dim=0)   # [K,B,C]
                    traj_conf_mean = torch.stack(confs, dim=0).mean()
                    if self.freeze_traj_bn:
                        self.model.train()
                    B = x_ulb_w.shape[0]
                    K = traj_probs.shape[0]

                    pseudo_src = probs_x_ulb_w
                    if self.a3_enable and self.it >= self.a3_warmup_iter:
                        conf_per_k = traj_probs.max(dim=-1)[0]
                        best_k = conf_per_k.argmax(dim=0)
                        b_idx = torch.arange(B, device=best_k.device)
                        p_star = traj_probs[best_k, b_idx]
                        if self.a3_ramp_iter > 0:
                            prog = min(max((self.it - self.a3_warmup_iter) / float(self.a3_ramp_iter), 0.0), 1.0)
                        else:
                            prog = 1.0
                        lam = self.a3_mix_ratio * prog
                        pseudo_src = (1.0 - lam) * probs_x_ulb_w + lam * p_star
                        pseudo_src = pseudo_src / pseudo_src.sum(dim=-1, keepdim=True)
                    elif self.a2_enable:
                        pseudo_src = traj_probs.mean(dim=0)

                mask = self.call_hook("masking", "MaskingHook",
                                     logits_x_ulb=probs_x_ulb_w, softmax_x_ulb=False)
                pseudo_label = self.call_hook(
                    "gen_ulb_targets", "PseudoLabelingHook",
                    logits=pseudo_src, use_hard_label=self.use_hard_label,
                    T=self.T, softmax=False,
                )
                if self.a41_enable:
                    pseudo_w = self.call_hook(
                        "gen_ulb_targets", "PseudoLabelingHook",
                        logits=probs_x_ulb_w, use_hard_label=self.use_hard_label,
                        T=self.T, softmax=False,
                    )
                    loss_strong = self.consistency_loss(logits_x_ulb_s, pseudo_w, 'ce', mask=mask)
                    loss_traj_weak = self.consistency_loss(logits_x_ulb_w, pseudo_label, 'ce', mask=mask)
                    unsup_loss = loss_strong + self.lambda_a41_traj * loss_traj_weak
                else:
                    unsup_logits = logits_x_ulb_w if self.a4_enable else logits_x_ulb_s
                    unsup_loss = self.consistency_loss(unsup_logits, pseudo_label, 'ce', mask=mask)

            # ── BASELINE PATH: plain FixMatch (no trajectory at all) ────────────
            else:
                mask = self.call_hook("masking", "MaskingHook",
                                     logits_x_ulb=probs_x_ulb_w, softmax_x_ulb=False)
                pseudo_label = self.call_hook(
                    "gen_ulb_targets", "PseudoLabelingHook",
                    logits=probs_x_ulb_w, use_hard_label=self.use_hard_label,
                    T=self.T, softmax=False,
                )
                unsup_loss = self.consistency_loss(logits_x_ulb_s, pseudo_label, 'ce', mask=mask)
                B = x_ulb_w.shape[0]
                K = 0

            # ── Trajectory-level consistency loss L_cons (Eq. 8) ───────────────
            # traj_probs are from teacher (new path) or student (legacy path)
            # Uses teacher predictions → no collapse shortcut
            cons_loss = torch.tensor(0.0, device=x_ulb_w.device)
            if self.lambda_cons > 0 and traj_probs is not None:
                K_eff = traj_probs.shape[0]
                for k in range(K_eff - 1):
                    diff = traj_probs[k + 1] - traj_probs[k]    # [B, C]
                    cons_loss = cons_loss + (diff ** 2).sum(dim=-1).mean()
                cons_loss = cons_loss / (K_eff - 1)

            # ── Lyapunov stability loss (Eq. 11 pull term) ──────────────────────
            # L_lyap = (λ/2) · Σ_params ||θ_t - θ_s||²  (teacher as fixed target)
            lyap_loss = torch.tensor(0.0, device=x_ulb_w.device)
            if self.lyap_enable and self.lyap_lambda > 0 and hasattr(self, 'ema') and self.ema is not None:
                for name, p_s in self.model.named_parameters():
                    p_t = self.ema.shadow.get(name)
                    if p_t is not None:
                        lyap_loss = lyap_loss + 0.5 * (p_s - p_t.detach()).pow(2).sum()

            total_loss = (sup_loss
                          + self.lambda_u * unsup_loss
                          + self.lambda_cons * cons_loss
                          + self.lyap_lambda * lyap_loss)

        # ── LyapEMA: set adaptive decay before EMAHook runs after_train_step ───
        # EMAHook.after_train_step calls ema.update() which reads self.ema.decay.
        # We write the adaptive α_t here; ParamUpdateHook has not run yet at this
        # point so we use the pre-update student params (valid approximation).
        if self.lyap_enable:
            self._update_lyap_decay()

        out_dict = self.process_out_dict(loss=total_loss, feat=feat_dict)
        log_dict = self.process_log_dict(
            sup_loss=sup_loss.item(),
            unsup_loss=unsup_loss.item(),
            cons_loss=cons_loss.item(),
            lyap_loss=lyap_loss.item(),
            total_loss=total_loss.item(),
            util_ratio=mask.float().mean().item(),
            traj_conf=traj_conf_mean.item(),
            ema_decay=self._last_alpha_t,
        )
        return out_dict, log_dict

    @staticmethod
    def get_argument():
        return [
            # ── Paper (new) arguments ──────────────────────────────────────────
            SSL_Argument('--hard_label', str2bool, True),
            SSL_Argument('--T', float, 0.5),
            SSL_Argument('--p_cutoff', float, 0.95),
            SSL_Argument('--traj_steps', int, 5),
            SSL_Argument('--traj_n_ops', int, 2),
            SSL_Argument('--lambda_cons', float, 0.0),
            SSL_Argument('--lyap_enable', str2bool, False),
            SSL_Argument('--lyap_gamma', float, 0.02),
            SSL_Argument('--lyap_lambda', float, 0.0),
            # ── Legacy arguments (backward compat) ────────────────────────────
            SSL_Argument('--a1_enable', str2bool, False),
            SSL_Argument('--a2_enable', str2bool, False),
            SSL_Argument('--a3_enable', str2bool, False),
            SSL_Argument('--a3_warmup_iter', int, 20000),
            SSL_Argument('--a3_mix_ratio', float, 0.2),
            SSL_Argument('--a3_ramp_iter', int, 30000),
            SSL_Argument('--a4_enable', str2bool, False),
            SSL_Argument('--a41_enable', str2bool, False),
            SSL_Argument('--lambda_a41_traj', float, 0.5),
            SSL_Argument('--a32_enable', str2bool, False),
            SSL_Argument('--traj_drop_max', float, 0.3),
            SSL_Argument('--traj_noise_max', float, 0.06),
            SSL_Argument('--traj_jitter_max', float, 0.2),
            SSL_Argument('--freeze_traj_bn', str2bool, False),
        ]
